export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const SAVE_SETTINGS = 'SAVE_SETTINGS';

export const GENERATE_SUMMARY = 'GENERATE_SUMMARY';
export const RECEIVE_SUMMARY = 'RECEIVE_SUMMARY';
