export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const SAVE_FORMATTER = 'SAVE_FOMATTER';
export const SAVE_DATE_RANGE = 'SAVE_DATE_RANGE';

export const SUMMARY_FETCH_REQUEST = 'SUMMARY_FETCH_REQUEST';
export const SUMMARY_FETCH_SUCCESS = 'SUMMARY_FETCH_SUCCESS';
export const SUMMARY_FETCH_FAIL = 'SUMMARY_FETCH_FAIL';
